# .github/workflows/deploy-lambda.yaml

name: Deploy Lambda Code to S3

# Trigger this workflow on pushes to the main branch
on:
  push:
    branches:
      - main # Or 'master', or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    # Define environment variables - CHANGE THESE!
    env:
      AWS_REGION: "us-east-1" # Change to your desired AWS region
      S3_BUCKET_NAME: "polly-tts-api-stack-audiobucket-pauif5zfe9qf" # Change to your actual S3 bucket name
      S3_OBJECT_KEY: "Text-to-speech/lambda_code.zip" # Change to your desired object key (path/filename.zip)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip Lambda function code
        run: |
          echo "Zipping index.py..."
          zip deployment_package.zip index.py
          echo "Created deployment_package.zip"

      - name: Upload zip file to S3
        run: |
          echo "Uploading deployment_package.zip to s3://${{ env.S3_BUCKET_NAME }}/${{ env.S3_OBJECT_KEY }}"
          aws s3 cp deployment_package.zip s3://${{ env.S3_BUCKET_NAME }}/${{ env.S3_OBJECT_KEY }}
          echo "Upload complete."